# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: DRL for Real ICCV Workshop 2025
short_description: Disentangled Representation Learning for Real-world Applications
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leaderboard for the DRL for Real competition, evaluating disentangled representation learning methods on realistic datasets. Models are ranked based on their performance in disentanglement, robustness, interpretability, and practical utility in real-world applications.
evaluation_script: evaluation_script.zip
remote_evaluation: True
start_date: 2025-05-31 00:00:00
end_date: 2025-6-30 23:59:59
published: True
tags: 
  - disentangled-representation-learning
  - computer-vision
  - interpretability
  - generative-models
leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Disentanglement", "Robustness", "Interpretability", "Practical Utility", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "Disentanglement": {
            "sort_ascending": False,
            "description": "Measures how well the model separates different factors of variation in the data.",
          },
          "Robustness": {
            "sort_ascending": False,
            "description": "Evaluates model performance under different real-world conditions and perturbations.",
          },
          "Interpretability": {
            "sort_ascending": False,
            "description": "Assesses how easily humans can understand the learned representations.",
          },
          "Practical Utility": {
            "sort_ascending": False,
            "description": "Measures the practical usefulness of the disentangled representations in downstream tasks.",
          }
        }
      }

challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    challenge: 1
    is_active: True
    max_concurrent_submissions_allowed: 3
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2025-05-31 00:00:00
    end_date: 2025-06-23 00:00:00
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev
    max_submissions_per_day: 50
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      # - name: TextAttribute
      #   description: Sample
      #   type: text
      #   required: False
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["AutoDrive", "ImageEditing", "Disentanglement"]
        required: True
      # - name: MultipleChoiceAttribute
      #   description: Sample
      #   type: checkbox
      #   options: ["alpha", "beta", "gamma"]
      # - name: TrueFalseField
      #   description: Sample
      #   type: boolean
      #   required: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz"
  - id: 2
    name: Test Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    challenge: 2
    is_active: True
    max_concurrent_submissions_allowed: 3
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2025-06-23 00:00:00
    end_date: 2025-06-30 23:59:59
    test_annotation_file: annotations/test_annotations_testsplit.json
    codename: test
    max_submissions_per_day: 50
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      # - name: TextAttribute
      #   description: Sample
      #   type: text
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      # - name: MultipleChoiceAttribute
      #   description: Sample
      #   type: checkbox
      #   options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    show_execution_time: False
    show_leaderboard_by_latest_submission: False
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
